name: 'Build HydePHP Site'
description: 'Build and deploy the HydePHP project'
runs:
  using: "composite"
  steps:
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
      shell: bash

    - name: Install dependencies
      run: composer install
      shell: bash

    - name: Build the site
      run: php hyde build
      shell: bash
