name: 'Build HydePHP Site'
description: 'Build and deploy the HydePHP project'
runs:
  using: "composite"
  steps:
    - run: composer install
      shell: bash

    - run: php hyde build
      shell: bash
