name: 'Build HydePHP Site'
description: 'Build and deploy the HydePHP project'
runs:
  using: "composite"
  steps:
    - name: Determine install strategy
      id: install-strategy
      run: |
        if [[ -f composer.json ]]; then
          echo "name=install-strategy::composer" >> $GITHUB_OUTPUT
        else
          echo "name=install-strategy::archive" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Validate composer.json and composer.lock
      if: steps.install-strategy.outputs.install-strategy == 'composer'
      run: composer validate --strict
      shell: bash

    - name: Cache Composer packages
      id: composer-cache
      if: steps.install-strategy.outputs.install-strategy == 'composer'
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Download latest release
      if: steps.install-strategy.outputs.install-strategy == 'archive'
      run: |
        # Copy all root files to backup directory
        cp -r . ../backup
        # Download latest version of HydePHP
        git clone https://github.com/hydephp/hyde.git ../hyde --depth 1
        # Copy HydePHP files to root
        cp -r ../hyde/* .
        # Copy Backup files to root
        cp -r ../backup/* .
      shell: bash

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-autoloader --no-dev && composer dump-autoload --quiet
      shell: bash

    - name: Build the site
      run: php hyde build --no-interaction --ansi
      shell: bash
