name: Continuous Integration

on:
  push:
    branches:
      - support-environment-variables

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hydephp/action@master
        with:
          debug: true
          upload-artifact: true

  build-documentation:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://hydephp.github.io/action
    steps:
      - uses: actions/checkout@v3
      - uses: hydephp/action@support-environment-variables
        with:
          deploy: pages
          env-torchlight-token: ${{ secrets.TORCHLIGHT_TOKEN }}
