name: Test Suite

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run linter
        run: php tests/lint.php

  run-workflow-test-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run workflow test 1
        uses: ./

  run-workflow-test-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run workflow test 2
        uses: ./
        with:
          debug: true

  run-workflow-test-3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run workflow test 3
        uses: ./
        with:
          deploy: artifact

  run-workflow-test-4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup project
        run: |
          composer create-project hyde/hyde --no-interaction --no-progress --no-dev /tmp/hyde
          cp -r /tmp/hyde/* .

      - name: Run workflow test 4
        uses: ./

  integration-tests:
    runs-on: ubuntu-latest
    name: "Integration test: ${{ matrix.test.name }}"
    strategy:
      fail-fast: false
      matrix:
        test:
          - name: "Full HydePHP project"
            id: "github-action-test-project-1"
          # - name: "Integration test 2"
          # - name: "Integration test 3"
    steps:
      - uses: actions/checkout@v3

      - name: Dispatch integration test ${{ matrix.test.id }}
        # Trigger workflow named test.yml in https://github.com/hyde-staging/${{ matrix.test.id }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.HYDE_STAGING_DISPATCH_TOKEN }}
          repository: hyde-staging/${{ matrix.test.id }}
          event-type: integration-test
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
