name: Test Suite

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-test-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run test 1
        uses: ./

  run-test-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run test 2
        uses: ./
        with:
          debug: true

  run-test-3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run test 3
        uses: ./
        with:
          deploy: artifact

  run-test-4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup project
        run: |
          composer create-project hyde/hyde --no-interaction --no-progress --no-dev /tmp/hyde
          cp -r /tmp/hyde/* .

      - name: Run test 4
        uses: ./

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run linter
        run: php tests/lint.php
