on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  integration-test-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Integration test 1
        uses: ./

  integration-test-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Integration test 2
        uses: ./
        with:
          debug: true

  integration-test-3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Integration test 3
        uses: ./
        with:
          deploy: artifact
