on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Integration test 1
        uses: ./

      - name: Integration test 2
        uses: ./
        with:
          debug: true
